#!/bin/bash

set -o errexit -o nounset -o pipefail

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already processing/deploying static files >&2
    exit 1
fi

./process-static $fd

servers=({0..7}.releases.katyasystem.org)

for server in ${servers[@]}; do
    echo $server

    remote=root@$server
    active=$(ssh $remote readlink /srv/apps.katyasystem.org)

    if [[ $active = /srv/apps.katyasystem.org_a ]]; then
        target=/srv/apps.katyasystem.org_b
    else
        target=/srv/apps.katyasystem.org_a
    fi

    echo active is $active
    echo target is $target
    echo

    ssh $remote "rm -rf $target && cp -a $active $target"
    rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate static-tmp/ $remote:$target
    ssh $remote "ln -snf $target /srv/apps.katyasystem.org && sync /srv/apps.katyasystem.org"

    echo "root $target;" > root_apps.katyasystem.org.conf
    rsync -ptcv --chmod=644 --fsync --preallocate root_apps.katyasystem.org.conf $remote:/etc/nginx/
    ssh $remote nginx -s reload

    echo
    echo active is now $target
    echo
done
